# Generated by Django 6.0.6 on 2026-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('last_accepted_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('heart_rate_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('spo2_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('motion', models.JSONField(blank=True, null=True)),
                ('sync_request_id', models.CharField(blank=True, max_length=100)),
                ('batch_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['device_id', 'sequence'],
                'unique_together': {('device_id', 'sequence')},
            },
        ),
    ]
