# Generated by Django 6.0.6 on 2026-06-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('firmware_version', models.CharField(max_length=50)),
                ('hardware_revision', models.CharField(max_length=50)),
                ('supported_sensor_modules', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('error', 'Error')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('last_accepted_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('study_name', models.CharField(max_length=255)),
                ('anonymized_participant_id', models.CharField(max_length=100)),
                ('enabled_sensor_modules', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_sessions', to='syncapi.device')),
            ],
        ),
        migrations.CreateModel(
            name='SensorBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_batches', to='syncapi.device')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_batches', to='syncapi.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True)),
                ('values', models.JSONField()),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='syncapi.sensorbatch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_readings', to='syncapi.device')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_readings', to='syncapi.studysession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'sensor_type', 'timestamp'], name='syncapi_sen_session_0c7e23_idx'), models.Index(fields=['device', 'sensor_type', 'timestamp'], name='syncapi_sen_device__1b3be3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sensorbatch',
            constraint=models.UniqueConstraint(fields=('device', 'batch_id'), name='unique_batch_per_device'),
        ),
    ]
