# Generated by Django 6.0.6 on 2026-06-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceSyncState',
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['session', 'sensor_type', 'timestamp']},
        ),
    ]
